### ISSUE TITLE
API users receive an email confirmation message

### ISSUE THREAD

**Issue by alexmuller** [alphagov/signonotron2#249]
When I create an API user with the `rake` task, the email address I specify receives an email change message:

> Confirm your email change

> Hello $API_USER,

> You can confirm the email change through the link below:

> Confirm my account

The API user doesn't have a password attached, so when I click the link and am taken to a form asking for a passphrase, I can't do anything.

**Comment by boffbowsh** [comment]
The mentioned UI now exists
