### ISSUE TITLE
Idea: PostgreSQL / Could Foundry

### ISSUE THREAD

**Issue by matthewford** [alphagov/signonotron2#465]
We're setting up an instance of trade tariff on Government PaaS Cloud Foundry.

Tariff Admin uses signonotron2 so we have a fork which uses PostgreSQL, and some changes to make running on CF easier. 

I can see some overlap, with the 12factor logging PR, so I wonder if it's worth consolidating the efforts.

https://github.com/alphagov/signonotron2/compare/master...bitzesty:postgresql

https://github.com/alphagov/signonotron2/compare/master...bitzesty:cf

**Comment by benilovj** [comment]
Thanks @matthewford
@alphagov/team-gov-uk-core-formats-and-publishing it'd be nice to move Signon to Postgres, and the bitzesty branches make it seem like it ought to be relatively straightforward.

**Comment by benlovell** [comment]
The technical side of this not such an issue, it's more about the effort required for us (being the core formats team) to perform the actual migration of data and such I guess.

**Comment by benilovj** [comment]
@benlovell: that's true. Still, we have some prior art with the [Support API](https://github.com/alphagov/support-api/pull/63) and despite having to optimise some queries for performance, that migration was relatively straightforward...

**Comment by boffbowsh** [comment]
We'll add this to our backlog. @matthewford if you can create a PR similar to https://github.com/alphagov/support-api/pull/63 which supports both MySQL and Postgres, it might make maintenance easier for everyone.

**Comment by matthewford** [comment]
@boffbowsh Sure, I'll take a look at that PR see if we can do something similar.

**Comment by matthewford** [comment]
Closed by #467
