### ISSUE TITLE
Log IP addresses in the event log

### ISSUE THREAD

**Issue by alexmuller** [alphagov/signonotron2#478]
It would be really useful if the event log stored the remote IP address where the action took place (especially for passphrase resets and logins).

The entire IP address would be useful but we could drop the last octet if we were required to.

**Comment by boffbowsh** [comment]
Can you give us a user need for this please Alex? Then I can write it up as a ticket in our backlog.

**Comment by alexmuller** [comment]
Sure, thanks! The most recent case was trying to match requests from a webserver access log, currently the only thing we can use is the timestamp. But it would also be useful when doing all kind of analysis into whether an account has been compromised or accessed from another location.

**Comment by boffbowsh** [comment]
Tracked at https://trello.com/c/YS8Xoxkp/467-add-ip-address-logging-to-signon-event-log
