### ISSUE TITLE
Set Passphrase (Accept Invitation) screen has two submit buttons

### ISSUE THREAD

**Issue by 36degrees** [alphagov/signonotron2#502]
When clicking through to accept an invitation, the set passphrase screen shows two submit buttons, one labelled '"Change passphrase" and the other labelled "Set my passphrase". Both seem to take the same action.

This is confusing.

By the looks of it, this is because the edit screen has its [own submit button](https://github.com/alphagov/signonotron2/blob/da6182f268a3e7ef91e2c547b40fe63316f9423e/app/views/devise/invitations/edit.html.erb#L13) but includes the `change_password_panel` partial which [includes another one](https://github.com/alphagov/signonotron2/blob/da6182f268a3e7ef91e2c547b40fe63316f9423e/app/views/devise/passwords/_change_password_panel.html.erb#L69).

I'd try and create a PR myself but I'm not sure what the desired change would be / which button should remain…

**Comment by timblair** [comment]
I noticed this today when setting up my account:

![change-or-set](https://cloud.githubusercontent.com/assets/3360/16622044/8b024dbe-4390-11e6-9bea-91bdf7f84fd9.png)

From a phrasing perspective, I'd suggest that "Set my passphrase" is correct for this page (it matches the page title / what the user is being asked to do).
